settings:
  title: 'Únete a la AED'
  body: '<p>La Asociación Española de Drupal crece cada año. Empresas, autónomos, y estudiantes forman una de las familias más influyentes del desarrollo web nacional.</p>'
