settings:
  title: 'Conviértete en patrocinador'
  body: '<p>Patrocina el evento y obtén a cambio difusión de tu marca.</p>'
  download_text: 'Descarga el dossier'
  download_url: 'https://drive.google.com/open?id=0B5Zv1LP5pgikZVd1SktNWHZaTEE'
