settings:
  title: 'Participa en la comunidad'
  body: '<p>La comunidad espa침ola de Drupal crece cada a침o. Empresas, aut칩nomos, y estudiantes forman parte de una de las familias m치s influyentes en la industria web.</p>'
  link_text: 'Hazte socio'
