settings:
  body: "<p>Dos días de charlas, talleres, y networking entorno al gestor de contenidos Drupal.</p>\r\n<p>El objetivo de la DrupalCamp es difundir y compartir el uso de Drupal en la industria web y servir como punto de encuentro para la comunidad española.</p>"
