settings:
  title: 'Hazlo con Drupal'
  body: "<p>Dos días de charlas, talleres y networking sobre el mejor gestor de contenidos.</p>\r\n<p>La DrupalCamp tiene como objetivo fomentar el uso de Drupal en España y ser el punto de encuentro de su comunidad.</p>"
