settings:
  body: "<p>La DrupalCamp reúne durante un fin de semana a los mejores expertos del sector.</p>\r\n<p>El objetivo de la DrupalCamp es difundir y compartir las tendencias de la industria del desarrollo web Drupal y sirve como punto de encuentro para la comunidad española.</p>"
