settings:
  title: 'Únete a la comunidad'
  body: '<p>La comunidad Drupal en España va aumentando año a año. Cada vez son más empresas, autónomos o estudiantes que se unen a una de las familias más influyentes del desarrollo web nacional.</p>'
