settings:
  title: 'Hazte grande patrocinando'
  body: "<p>Ponte en contacto con nosotros en asociacion arroba drupal punto es si estás interesado en promocionar tu empresa patrocinando el evento. Publicaremos los packs de patrocinio muy pronto.</p>\r\n\r\n<p>Alternativamente, apúntate al newsletter al final de esta página.</p>"
