label: Language
tips:
  language-overview:
    label: Languages
    body: '<p>The "Languages" page allows you to add, edit, delete, and reorder languages for the site.</p>'
  language-add:
    label: 'Añadiendo idiomas'
    body: '<p>Para añadir más idiomas a su sitio, haga clic en el botón "Añadir idioma".</p><p>Los idiomas añadidos se mostrarán en la lista de idiomas y pueden entonces ser editados o borrados.</p>'
  language-reorder:
    label: 'Reordering languages'
    body: '<p>Para cambiar el orden de los idiomas en su sitio, utilice los iconos de selección junto a cada idioma.</p><p>El orden que se muestra aquí es el orden de presentación de las listas de idiomas en el sitio como en los bloques selectores de idiomas proporcionados por los módulos Interface Translation  y Content Translation.</p><p>Cuando haya terminado con la reordenación de los idiomas, haga clic en el botón "Guardar configuración" para que los cambios surtan efecto.</p>'
  language-default:
    label: 'Set a language as default'
    body: '<p>Se puede cambiar el idioma predeterminado del sitio por uno de los idiomas configurados por defecto. El sitio utilizará el idioma predeterminado cuando se necesite tener seleccionado un idioma pero no se haya elegido ninguno. Como por ejemplo el idioma de la interfaz mostrada.</p>'
  language-operations:
    label: 'Modificando idiomas'
    body: '<p>Las operaciones son proporcionadas para editar y eliminar sus idiomas.</p><p>Puede editar el nombre y la dirección de un idioma.</p><p>Los idiomas eliminados pueden ser nuevamente añadidos en otro momento. Eliminar un idioma removerá todas las traducciones de la interfaz asociadas con él, y el contenido en este idioma será establecido como idioma neutral. Tenga en cuenta que no puede eliminar el idioma predeterminado para su sitio.</p>'
  language-continue:
    label: Continuando
    body: '<p>Now that you have an overview of the "Languages" page, you can continue by:<ul><li><a href="[site:url]/admin/config/regional/language/add">Adding a language</a></li><li>Reordering languages</li><li>Editing a language</li><li>Deleting a language</li></ul></p>'
