label: Idioma
tips:
  language-overview:
    label: Idiomas
    body: '<p>La p치gina "Idiomas" le permite a침adir, editar, borrar y reordenar los idiomas para el sitio.</p>'
  language-add:
    label: 'Adding languages'
    body: '<p>To add more languages to your site, click the "Add language" button.</p><p>Added languages will be displayed in the language list and can then be edited or deleted.</p>'
  language-reorder:
    label: 'Reordering languages'
    body: '<p>To reorder the languages on your site, use the drag icons next to each language.</p><p>The order shown here is the display order for language lists on the site such as in the language switcher blocks provided by the Interface Translation and Content Translation modules.</p><p>When you are done with reordering the languages, click the "Save configuration" button for the changes to take effect.</p>'
  language-default:
    label: 'Esteblacer un idioma como predeterminado'
    body: '<p>You can change the default language of the site by choosing one of your configured languages as default. The site will use the default language in situations where no choice is made but a language should be set, for example as the language of the displayed interface.</p>'
  language-operations:
    label: 'Modifying languages'
    body: '<p>Operations are provided for editing and deleting your languages.</p><p>You can edit the name and the direction of the language.</p><p>Deleted languages can be added back at a later time. Deleting a language will remove all interface translations associated with it, and content in this language will be set to be language neutral. Note that you cannot delete the default language of the site.</p>'
  language-continue:
    label: 'Continuing on'
    body: '<p>Ahora que tiene una vista general de la p치gina de "Idiomas", puede continuar con:<ul><li><a href="[site:url]/admin/config/regional/language/add">A침adir un idioma</a></li><li>Reordenar idiomas</li><li>Editar un idioma</li><li>Eliminar un idioma</li></ul></p>'
