label: Translation
tips:
  locale-overview:
    label: 'User interface translation'
    body: 'This page allows you to translate the user interface or modify existing translations. If you have installed your site initially in English, you must first add another language on the <a href="[site:url]/admin/config/regional/language">Languages page</a>, in order to use this page.'
  locale-language:
    label: 'Translation language'
    body: 'Choose the language you want to translate.'
  locale-search:
    label: Search
    body: 'Intruduzca la palabra u oración específica que usted desea traducir, también puede escribir solamente una parte de la palabra.'
  locale-filter:
    label: 'Filtrar la búsqueda'
    body: 'Puede buscar cadenas no traducidas si quiere traducir algo que todavía no está traducido. Si quiere modificar una traducción exitente, podría querer buscar solo cadenas traducidas.'
  locale-submit:
    label: 'Aplicar sus criterios de búsqueda'
    body: 'Para aplicar su criterio de búsqueda, haga click en el botón <em>Filtrar</em>.'
  locale-translate:
    label: Translate
    body: 'Puede escribir su propia traducción en los campos de texto en la columna de la derecha. Intente fijarse en cual contexto el texto será usado para traducirlo de la manera apropiada.'
  locale-validate:
    label: 'Validar la traducción'
    body: 'Cuando haya terminado sus traducciones, haga clic en el botón <em>Guardar traducciones</em>. Usted debe guardar sus traducciones, cada vez antes de cambiar de página o hacer una nueva búsqueda.'
  locale-continue:
    label: Continuando
    body: 'The translations you have made here will be used on your site''s user interface. If you want to use them on another site or modify them on an external translation editor, you can <a href="[site:url]/admin/config/regional/translate/export">export them</a> to a .po file and <a href="[site:url]/admin/config/regional/translate/import">import them</a> later.'
