label: Glosario
description: 'Todo el contenido, alfabéticamente.'
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'elementos por página'
            items_per_page_options_all_label: '— Todo(s) —'
            offset_label: Desplazamiento
          tags:
            previous: ‹‹
            next: ››
      fields:
        title:
          label: Título
        name:
          label: Autor
        changed:
          label: 'Última actualización'
  attachment_1:
    display_title: Adjunto
  page_1:
    display_title: Página
    display_options:
      menu:
        title: Glosario
