description: 'Muestra los nombres de usuario de los usuarios recientes más activos y el número total de usuarios activos.'
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          reset_button_label: Reiniciar
      filters:
        access:
          expose:
            label: 'Último acceso'
            description: 'Se considera que un usuario está conectado este periodo después de que haya visto esta página por última vez.'
      title: 'Quién está conectado'
  who_s_online_block:
    display_title: 'Quién está conectado'
    display_options:
      block_description: 'Quién está conectado'
