label: Redirect
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ anterior'
            next: 'siguiente ›'
            first: '« primera'
            last: 'última »'
          expose:
            items_per_page_label: 'elementos por página'
            items_per_page_options_all_label: '— Todo(s) —'
            offset_label: Desplazamiento
      fields:
        redirect_bulk_form:
          action_title: 'With selection'
        redirect_source__path:
          label: From
          separator: ', '
        created:
          label: Created
      filters:
        redirect_source__path:
          expose:
            label: From
        redirect_redirect__uri:
          expose:
            label: To
        status_code:
          expose:
            label: 'Status code'
          group_info:
            label: 'Status code'
        language:
          expose:
            label: 'Original language'
      title: Redirect
  page_1:
    display_title: Página
