label: Archive
description: 'All content, by month.'
display:
  default:
    display_title: Máster
    display_options:
      title: 'Monthly archive'
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'elementos por página'
            items_per_page_options_all_label: '— Todo(s) —'
            offset_label: Desplazamiento
          tags:
            previous: ‹‹
            next: ››
      arguments:
        created_year_month:
          title: '{{ arguments.created_year_month }}'
  block_1:
    display_title: Bloque
    display_options:
      arguments:
        created_year_month:
          title: '{{ arguments.created_year_month }}'
  page_1:
    display_title: Página
