dcamp.dcamp.*:
  type: config_entity
  label: 'DrupalCamp Configuration Entity'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    landing_theme:
      type: string
      label: 'Landing Theme'
    starting_date:
      type: string
      label: 'Starting Date'

block.settings.dcamp_landing_info_with_countdown_block:
  type: block_settings
  label: 'Landing Info With Countdown Block'
  mapping:
    title:
      type: text
      label: 'Title'
    body:
      type: text
      label: 'Body'
