<?php

/**
 * @file
 *
 * Hook implementations for dcamp_attendees module.
 */

/**
 * Implements hook_theme().
 */
function dcamp_attendees_theme($existing, $type, $theme, $path) {
  return array(
    'attendees_list' => array(
      'variables' => array(
        'attendees' => [],
        'default_headshot' => base_path() . drupal_get_path('theme', 'dcamp_2020_theme') . '/images/drupal.png',
      ),
    ),
  );
}
