- name: Deploy to "{{ ansistrano_deploy_to }}"
  hosts: all 
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/../"
    ansistrano_shared_paths:
      - 'web/sites/default/files'
      - 'web/sites/default/private'
    ansistrano_shared_files:
      - 'web/sites/default/settings.local.php'
    ansistrano_keep_releases: 5
    ansistrano_rsync_extra_params: "--exclude '.git' --exclude 'ansible'  --exclude '.DS_Store' --exclude 'ehthumbs.db' --exclude 'Thumbs.db' --exclude 'web/sites/default/settings.local.php' --delete-excluded"
    ansistrano_allow_anonymous_stats: false
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/tasks/after-symlink-tasks.yml"
    drupal_rel_path : '/web'
    drush_args : ''

  pre_tasks: 
  - name: 'Run composer'
    local_action: composer command=install no-dev=yes optimize-autoloader=yes working_dir="{{ ansistrano_deploy_from }}"

  roles:
    - role: carlosbuenosvinos.ansistrano-deploy

